import { 
   LayoutDashboard,
   Users, 
   Search, 
   Bell, 
   Settings, 
   BarChart3,
   Plus,
   ArrowRightIcon,
   User,
   Shield,
   Palette,
   Globe,
   Sun,
   Moon,
   Monitor,
   LogOut,
   BookOpen,
   CheckCircle,
   FileText,
   Clock,
   UserPlus,
   ArrowLeft,
   Check,
   Trash2,
   Database,
   ClipboardList,
   GraduationCap,
   Loader2,
   Eye,
  } from "lucide-react";
export const Icons = {
  Eye: Eye,
  Loader2: Loader2,
  GraduationCap: GraduationCap,
  ClipboardList: ClipboardList,
  Database: Database,
  Trash2: Trash2,
  Check: Check,
  ArrowLeft: ArrowLeft,
  UserPlus: UserPlus,
  FileText: FileText,
  BookOpen: BookOpen,
  CheckCircle: CheckCircle,
  Search: Search,
  Bell: Bell,
  Dashboard: LayoutDashboard,
  Users: Users,
  Chart: BarChart3,
  Settings: Settings,
  Plus: Plus,
  ArrowRight: ArrowRightIcon,
  User: User,
  Shield: Shield,
  Palette: Palette,
  Globe: Globe,
  Sun: Sun,
  Moon: Moon,
  Monitor: Monitor,
  Logout: LogOut,
  Clock: Clock,
};

