import {
  LayoutDashboard,
  Users,
  Search,
  Bell,
  Settings,
  BarChart3,
  Plus,
  ArrowRightIcon,
  User,
  Shield,
  Palette,
  Globe,
  Sun,
  Moon,
  Monitor,
  LogOut,
  BookOpen,
  CheckCircle,
  FileText,
  Clock,
  UserPlus,
  ArrowLeft,
  Check,
  Trash2,
  Database,
  ClipboardList,
  GraduationCap,
  Loader2,
  Eye,
  Sparkles,
  ChevronLeft,
  Mail,
  Lock,
  EyeOff,
  TrendingUp,
  TrendingDown,
  Save,
  Key,
  PanelLeft,
  Maximize2,
  Minimize2,
  RefreshCw,
  AlertTriangle,
  Calendar,
  Backpack,
  Edit,
  Trash,
  XCircle,
  ScrollText,
  Minus,
  Zap,
  ChevronRight,
  Languages,
  SlidersHorizontal,
  Star,
  ChevronDown,
  Award,
  ArchiveRestore,
  MessageCircle,
  X
} from "lucide-react";
export const Icons = {
  X: X,
  MessageCircle: MessageCircle,
  ArchiveRestore: ArchiveRestore,
  Award: Award,
  ChevronDown: ChevronDown,
  Star: Star,
  Languages: Languages,
  SlidersHorizontal: SlidersHorizontal,
  Zap: Zap,
  Minus: Minus,
  ChevronRight: ChevronRight,
  ScrollText: ScrollText,
  XCircle: XCircle,
  Trash: Trash,
  Edit: Edit,
  Backpack: Backpack,
  Calendar: Calendar,
  AlertTriangle: AlertTriangle,
  RefreshCw: RefreshCw,
  Maximize2: Maximize2,
  Minimize2: Minimize2,
  PanelLeft: PanelLeft,
  Save: Save,
  Key: Key,
  TrendingUp: TrendingUp,
  TrendingDown: TrendingDown,
  Mail: Mail,
  Lock: Lock,
  EyeOff: EyeOff,
  ChevronLeft: ChevronLeft,
  Sparkles: Sparkles,
  Eye: Eye,
  Loader2: Loader2,
  GraduationCap: GraduationCap,
  ClipboardList: ClipboardList,
  Database: Database,
  Trash2: Trash2,
  Check: Check,
  ArrowLeft: ArrowLeft,
  UserPlus: UserPlus,
  FileText: FileText,
  BookOpen: BookOpen,
  CheckCircle: CheckCircle,
  Search: Search,
  Bell: Bell,
  Dashboard: LayoutDashboard,
  Users: Users,
  Chart: BarChart3,
  Settings: Settings,
  Plus: Plus,
  ArrowRight: ArrowRightIcon,
  User: User,
  Shield: Shield,
  Palette: Palette,
  Globe: Globe,
  Sun: Sun,
  Moon: Moon,
  Monitor: Monitor,
  Logout: LogOut,
  Clock: Clock,
};

