import { 
  LayoutDashboardIcon,
   Users, 
   Search, 
   Bell, 
   Settings, 
   BarChart3,
   Plus,
   ArrowRightIcon,
   User,
   Shield,
   Palette,
   Globe,
   Sun,
   Moon,
   Monitor,
   LogOut,
   BookOpen,
   CheckCircle,
   FileText,
   Clock
  } from "lucide-react";
export const Icons =  {
  FileText: () => <FileText />,
  BookOpen: () => <BookOpen />,
  CheckCircle: () => <CheckCircle />,
  Search: () => <Search/>,
  Bell: () => <Bell/>,
  Dashboard: () => <LayoutDashboardIcon />,
  Users: () => <Users />,
  Chart: () => <BarChart3 />,
  Settings: () => <Settings />,
  Plus: () => <Plus/>,
  ArrowRight: () => <ArrowRightIcon />,
  User: () => <User />,
  Shield: () => <Shield />,
  Palette: () => <Palette />,
  Globe: () => <Globe />,
  Sun: () => <Sun />,
  Moon: () => <Moon />,
  Monitor: () => <Monitor />,
  Logout: () => <LogOut />,
  Clock: () => <Clock />,
};

